name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: 17
          apps: sbtn
      - name: Build + Lint + Test
        run: |
          sbt -v 'set ThisBuild / scalacOptions += "-Xfatal-warnings"; scalafmtCheckAll; test'
